name: Greetings

on: [push, pull_request_target, issues]

jobs:
  wso2:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: yasassri/setup-wso2-apictl@v0.9.1
      with:
        url: 'localhost'
