name: WSO2_APIM
on: [push, pull_request_target, issues]

jobs:
  wso2:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: yasassri/setup-wso2-apictl@v1.0
      with:
        version: 'v3.2.5'
    - run: apictl version
